---
.gitignore:
  required:
    - '---/Gemfile.lock'
    - '/modules/'
    - '/.librarian/'
    - '/.tmp/'

appveyor.yml:
  delete: true

.travis.yml:
  delete: true

.gitlab-ci.yml:
  override: true
  custom:
    cache:
      paths:
        - 'vendor/bundle'
    bundler_args: '--without system_tests --path vendor/bundle --jobs $(nproc)'
    custom_stages:
      - syntax
      - unit
    ruby_versions:
      '2.4.4':
        checks:
          - 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
          - parallel_spec
        puppet_version: '~> 5.5'
      '2.5.1':
        checks:
          - 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
          - parallel_spec
        puppet_version: '~> 6.0'

Rakefile:
  extras:
    - '### Import all tasks from the tasks dir:'
    - 'Dir.glob("tasks/*.rake").each do |rakefile|'
    - '  import rakefile'
    - 'end'

Gemfile:
  required:
    ':development':
      - gem: pry
    ':acceptance':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
      - gem: beaker-hiera
      - gem: beaker-docker
      - gem: beaker-vagrant

spec/spec_helper.rb:
  mock_with: ":rspec"
  spec_overrides: >-
    require 'pry'

    RSpec.configure do |c|
      c.after(:suite) do
        RSpec::Puppet::Coverage.report!(100)
      end
    end
